Minor script changes

diff --git a/msfvlist b/msfvlist
--- a/msfvlist
+++ b/msfvlist
@@ -12,8 +12,8 @@ usage() {
     echo
     echo "Options:"
     echo "   -h|--help              displays this help message"
-    echo "   -p|--payload payload   payload to list options for"
     echo "   -f|--filter filter     grep pattern to filter output by"
+    echo "   -p|--payload payload   payload to list options for"
     echo "   -u|--update            forces cache update"
     echo "   -v|--verbose           verbose output when displaying payloads, encoders,  and nops"
     exit 0
@@ -23,38 +23,13 @@ args=()
 
 while (( "$#" )); do
     case "$1" in
-        -h|--help)
-            usage
-            exit 0
-            ;;
-        -f|--filter)
-            filter=$2
-            shift 2
-            ;;
-        -p|--payload)
-            payload=$2
-            shift 2
-            ;;
-        -u|--update)
-            update=true
-            shift
-            ;;
-        -v|--verbose)
-            verbose=1
-            shift
-            ;;
-#        -vv)
-#            verbose=2
-#            shift
-#            ;;
-        -*)
-            echo "Error: Unsupported flag $1" >&2
-            exit 1
-            ;;
-        *)
-            args=( "${args[@]}" "$1" )
-            shift
-            ;;
+        -h|--help) usage;;
+        -f|--filter) filter=$2; shift 2;;
+        -p|--payload) payload=$2; shift 2;;
+        -u|--update) update=true; shift;;
+        -v|--verbose) verbose=1; shift;;
+        -*) echo "Error: Unsupported flag $1" >&2; exit 1;;
+        *) args=( "${args[@]}" "$1" ); shift;;
     esac
 done
 
@@ -83,7 +58,7 @@ output() {
         echo "Unable to read cache from $cache"
         exit 1
     fi
-    while IFS="" read -r p || [ -n "$p" ]; do
+    while IFS="" read -r p; do
         item=$(echo $p | cut -d " " -f 1)
         if [ $verbose > 0 ]; then
             echo -e ${GREEN}$item${NC}
@@ -137,3 +112,4 @@ else
     esac
 
 fi
+
